### ISSUE TITLE
FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE

### ISSUE THREAD

**Issue by lukacmilos** [browserstack/browserstack-local-java#25]
Hi,
I set my project according to this repository. It worked OK, but now some random tests are failed with following failure. Issue tends to appear randomly, without any detailed stacktrace. I think that implementation is correct, because majority of tests works, it means that RemoteWebDriver is created correctly and connected to browserstack. I'm using serenity with cucumber and tests run on BS. Please have you any idea?

11:54:16.369 [Test worker] ERROR n.t.core.webdriver.WebDriverFacade - FAILED TO CREATE NEW WEBDRIVER_DRIVER INSTANCE class net.thucydides.core.webdriver.ProvidedDriver: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (null
    net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate new WebDriver instance of type class net.thucydides.core.webdriver.ProvidedDriver (null
    	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:135)
    	at net.thucydides.core.webdriver.WebDriverFacade.newDriverInstance(WebDriverFacade.java:147)
    	at net.thucydides.core.webdriver.WebDriverFacade.newProxyDriver(WebDriverFacade.java:138)
    	at net.thucydides.core.webdriver.WebDriverFacade.getProxiedDriver(WebDriverFacade.java:108)
    	at net.thucydides.core.webdriver.WebDriverFacade.getDriverClass(WebDriverFacade.java:101)
    	at net.thucydides.core.webdriver.WebDriverType.isMobile(WebDriverType.java:9)
    	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.platformFor(ElementLocatorFactorySelector.java:48)
    	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:41)
    	at net.thucydides.core.webdriver.ElementLocatorFactorySelector.getLocatorFor(ElementLocatorFactorySelector.java:31)
    	at net.thucydides.core.annotations.locators.SmartElementProxyCreator.proxyElements(SmartElementProxyCreator.java:25)
    	at net.thucydides.core.webdriver.DefaultPageObjectInitialiser.apply(DefaultPageObjectInitialiser.java:21)
    	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:150)
    	at net.serenitybdd.core.pages.PageObject.setDriver(PageObject.java:154)
    	at net.serenitybdd.core.pages.PageObject.<init>(PageObject.java:139)
    	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.<init>(BrowseTheWeb.java:34)
    	at net.serenitybdd.screenplay.abilities.BrowseTheWeb.with(BrowseTheWeb.java:50)
    	at com.ui.common.GlobalBeforeAndAfter.uiUserCanBrowseWeb(GlobalBeforeAndAfter.java:30)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at cucumber.runtime.Utils$1.call(Utils.java:40)
    	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
    	at cucumber.runtime.Utils.invoke(Utils.java:34)
    	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
    	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
    	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
    	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
    	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
    	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
    	at org.junit.runners.Suite.runChild(Suite.java:128)
    	at org.junit.runners.Suite.runChild(Suite.java:27)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
    	at org.junit.runners.Suite.runChild(Suite.java:128)
    	at org.junit.runners.Suite.runChild(Suite.java:27)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
    	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
    	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
    	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
    	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
    	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
    	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
    	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
    	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
    	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
    	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.NullPointerException: null
    	at net.thucydides.core.webdriver.redimension.RedimensionConfiguration.supportsScreenResizing(RedimensionConfiguration.java:18)
    	at net.thucydides.core.webdriver.redimension.RedimensionStrategy.strategyFor(RedimensionStrategy.java:15)
    	at net.thucydides.core.webdriver.redimension.RedimensionBrowser.withDriver(RedimensionBrowser.java:31)
    	at net.thucydides.core.webdriver.WebDriverFactory.newWebdriverInstance(WebDriverFactory.java:127)

**Comment by michelmeeuwissen** [comment]
Same issue here,

Found any solution?

**Comment by mohitmun** [comment]
@lukacmilos, @michelmeeuwissen, @arnulfojr  can you let me on which os and os version are you using? Also mention browserstack-local-java version

**Comment by PratapSingh09** [comment]
Hey its resolved

**Comment by mghiraw** [comment]
Hi PratapSingh09
How did you resolved this?
We are also facing this.

**Comment by isabellogz** [comment]
Hi, I have same issue. How was fixed?

**Comment by mghiraw** [comment]
Hi I did not solve it, but we are getting it incidently.
For that we have a workarround.
I use a try and catch in a loop.


    @Step(value = "Open de standaard startpagina (portaal/login)")
    public void open_default_page() {
        boolean fireFox = false;
        int maxAantalKerenProberen = 10;
        int t = 0;
        while ((!fireFox) && (t < maxAantalKerenProberen)) {
            try {
                t++;
                configureFirefox();
                browser.reset();
                applicationPage.open(ApplicationPage.LOGINPAGE, new String[]{});
                fireFox =
getDriver().getCurrentUrl().contains("portaal") ? true : false;
            } catch (UnsupportedDriverException | WebDriverException e) {
                LOG.error("Fout bij het instantieren van de Firefox
Driver:", e);
                System.out.println("Fout bij het instantieren van de
Firefox Driver: " + e);
                configureFirefox();
                waitABit(5000);
            }
        }

        applicationPage.getDriver().manage().window().maximize();
        commonSteps.logNaarHtmlRapport("Opened page: ",
getDriver().getCurrentUrl());
    }

    @Step
    public void configureFirefox() {
        getDriver().quit();
        Serenity.getWebdriverManager().resetDriver();
        Serenity.getWebdriverManager().reset();
        Serenity.getWebdriverManager().closeDriver();
        FirefoxProfile myProfile = new FirefoxProfile();
        myProfile.setAlwaysLoadNoFocusLib(false);
        myProfile.setPreference("focusmanager.testmode", true);
        Serenity.useFirefoxProfile(myProfile);
    }


2018-07-26 11:50 GMT+02:00 isabellogz <notifications@github.com>:

**Comment by lukacmilos** [comment]
My problem was, that I had 2 jenkins jobs, each for one browser and I had more than one connection to BS, then I added localIdentifier(randomString) and my problem was solved.

**Comment by Amarsree12** [comment]
I have downloaded the the GIT repo from Browserstack.But when i try to run getting net.thucydides.core.webdriver.UnsupportedDriverException: Could not instantiate class net.thucydides.core.webdriver.ProvidedDriver error

Can anyone help on this?

**Comment by xescuder** [comment]
I've the same problem executing the git example of browserstack with serenity

**Comment by vayaszsolt** [comment]
Any news about this issue? I receive the same issue randomly. There are jenkins build where the RemoteWebDriver to browserstack can be created but also there are fails with the same message as in this issue is specified. I will welcome any suggestion how can I fix this issue, I spent a lot of time to find a fix for it.
